<a href="https://colab.research.google.com/github/aravind-thalla/Generative_AI_2303A52049/blob/main/Week_1_GenAI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
Y_act=[10,20,30,40,50]
Y_pred=[10.2,20.5,30.3,40.8,50.6]
n=len(Y_act)
MSE = 0
MAE = 0
RMSE=  0

for i in range(n):
    MSE = MSE + (Y_act[i] - Y_pred[i])**2
    MAE = MAE + abs(Y_act[i] - Y_pred[i])
    MSE = MSE/n
    MAE = MAE/n
    RMSE=MSE**0.5


print("MSE = ",MSE)
print("MAE = ",MAE)
print("RMSE = ",RMSE)



MSE =  0.09873280000000016
MAE =  0.15526400000000018
RMSE =  0.3142177588870498


In [2]:
import numpy as np
yact=[0,0,0,0,0,1,1,1,1,1,1,2,2,2,2,2]
ypred=[0,0,1,1,2,2,0,1,1,1,2,0,2,1,1,2]

l=[]
for i in range(len(yact)):
    l.append([yact[i],ypred[i]])
print(l)

[[0, 0], [0, 0], [0, 1], [0, 1], [0, 2], [1, 2], [1, 0], [1, 1], [1, 1], [1, 1], [1, 2], [2, 0], [2, 2], [2, 1], [2, 1], [2, 2]]

cm=[[l.count([0,0]),l.count([0,1]),l.count([0,2])],[l.count([1,0]),l.count([1,1]),l.count([1,2])],[l.count([2,0]),l.count([2,1]),l.count([2,2])]]
print("confusionmatrix of above data is:\n",np.array(cm))


import numpy as np

def calculate_precision_recall_f1(cm):
    num_classes = len(cm)
    precision = [0] * num_classes
    recall = [0] * num_classes
    f1_score = [0] * num_classes
    tp_mat = []
    fp_mat = []
    fn_mat = []
    tn_mat = []



num_classes = len(cm)


accuracy = 0
precision = [0] * num_classes
recall = [0] * num_classes
f1_score = [0] * num_classes



total_instances = sum(sum(row) for row in cm)

for i in range(num_classes):


    TP = cm[i][i]

    FP = sum(cm[row][i] for row in range(num_classes)) - TP

    FN = sum(cm[i]) - TP
    TN = total_instances - (TP + FP + FN)


    precision[i] = TP / (TP + FP) if TP + FP != 0 else 0
    recall[i] = TP / (TP + FN) if TP + FN != 0 else 0
    f1_score[i] = 2 * (precision[i] * recall[i]) / (precision[i] + recall[i]) if precision[i] + recall[i] != 0 else 0


    accuracy += TP

accuracy /= total_instances


print("Accuracy:", accuracy)
for i in range(num_classes):
    print(f"Class {i}:")
    print(f"  Precision: {precision[i]}")
    print(f"  Recall: {recall[i]}")
    print(f"  F1 Score: {f1_score[i]}")

[[0, 0], [0, 0], [0, 1], [0, 1], [0, 2], [1, 2], [1, 0], [1, 1], [1, 1], [1, 1], [1, 2], [2, 0], [2, 2], [2, 1], [2, 1], [2, 2]]
confusionmatrix of above data is:
 [[2 2 1]
 [1 3 2]
 [1 2 2]]
Accuracy: 0.4375
Class 0:
  Precision: 0.5
  Recall: 0.4
  F1 Score: 0.4444444444444445
Class 1:
  Precision: 0.42857142857142855
  Recall: 0.5
  F1 Score: 0.4615384615384615
Class 2:
  Precision: 0.4
  Recall: 0.4
  F1 Score: 0.4000000000000001
